spring:
  profiles:
    active: local

logging:
  config: classpath:logback.xml
  #path: classpath:log

trainer:
  metrics:
    configFile: src/main/resources/config.yml
    inputFile: src/main/resources/drivers.csv
    learnedInput: src/main/resources/drivers1.csv
    outputFile: src/main/resources/output.txt
    populationSize: 10
