spring:
  profiles:
    active: local

logging:
  config: classpath:logback-test.xml
  #path: classpath:src/tezt/resources

trainer:
  metrics:
    support: 0.5
    dataFile: classpath:data.csv

sunrise:
  data: src/main/java/ca/ucalgary/rules599/Training/sunlightData